FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
WORKDIR /work/
RUN chown root /work \
    && chmod "g+rwX" /work \
    && chown root:root /work
COPY --chown=root:root *-runner /work/application

EXPOSE 8089
USER root

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
